---

stackhpc_gitlab_runner_environment: vglab

gitlab_runner_coordinator_url: https://gitlab.com/

gitlab_runner_runners:
  - name: '{{ stackhpc_gitlab_runner_environment | uppercase }} AIO runner'
    executor: docker
    docker_image: 'centos:8'
    output_limit: 24576
    run_untagged: false
    tags:
      - "{{ stackhpc_gitlab_runner_environment }}"
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
      - "/certs/client"
      - "/dev:/dev"
    env_vars:
      - "TERRAFORM_OPENRC={{ lookup('file', '~/vglab.env') }}"
    extra_configs:
      runners.docker:
        tls_verify: false
        privileged: true

  - name: '{{ stackhpc_gitlab_runner_environment | uppercase }} Builder'
    executor: docker
    docker_image: 'centos:8'
    output_limit: 24576
    run_untagged: false
    tags:
      - "{{ stackhpc_gitlab_runner_environment }}-builder"
      - dind
    docker_volumes:
      - "/cache"
      - "/certs/client"
      - "/dev:/dev"
    extra_configs:
      runners.docker:
        tls_verify: false
        privileged: true

stackhpc_gitlab_runner_docker_mtu: 1442
